import { UserRole } from "@/types/authTypes";
import { PostCategory } from "@/types/postTypes";

export const POST_STYLES = {
  category: {
    [PostCategory.ALERT]: {
      gradient: "from-red-500 to-orange-500",
      bg: "bg-red-50 dark:bg-red-950/20",
      text: "text-red-700 dark:text-red-300",
      border: "border-red-200 dark:border-red-800",
      icon: "⚠️",
      glow: "shadow-red-500/20",
    },
    [PostCategory.INFORMATION]: {
      gradient: "from-cyan-500 to-blue-500",
      bg: "bg-cyan-50 dark:bg-cyan-950/20",
      text: "text-cyan-700 dark:text-cyan-300",
      border: "border-cyan-200 dark:border-cyan-800",
      icon: "ℹ️",
      glow: "shadow-cyan-500/20",
    },
    [PostCategory.ANNOUNCEMENT]: {
      gradient: "from-purple-500 to-pink-500",
      bg: "bg-purple-50 dark:bg-purple-950/20",
      text: "text-purple-700 dark:text-purple-300",
      border: "border-purple-200 dark:border-purple-800",
      icon: "📢",
      glow: "shadow-purple-500/20",
    },
    [PostCategory.EVENT]: {
      gradient: "from-pink-500 to-rose-500",
      bg: "bg-pink-50 dark:bg-pink-950/20",
      text: "text-pink-700 dark:text-pink-300",
      border: "border-pink-200 dark:border-pink-800",
      icon: "🎉",
      glow: "shadow-pink-500/20",
    },
    [PostCategory.JOB]: {
      gradient: "from-indigo-500 to-blue-500",
      bg: "bg-indigo-50 dark:bg-indigo-950/20",
      text: "text-indigo-700 dark:text-indigo-300",
      border: "border-indigo-200 dark:border-indigo-800",
      icon: "💼",
      glow: "shadow-indigo-500/20",
    },
    [PostCategory.LOST_FOUND]: {
      gradient: "from-yellow-500 to-amber-500",
      bg: "bg-yellow-50 dark:bg-yellow-950/20",
      text: "text-yellow-700 dark:text-yellow-300",
      border: "border-yellow-200 dark:border-yellow-800",
      icon: "🔍",
      glow: "shadow-yellow-500/20",
    },
    [PostCategory.OTHER]: {
      gradient: "from-gray-500 to-slate-500",
      bg: "bg-gray-50 dark:bg-gray-800/20",
      text: "text-gray-700 dark:text-gray-300",
      border: "border-gray-200 dark:border-gray-700",
      icon: "📌",
      glow: "shadow-gray-500/20",
    },
  },
  role: {
    [UserRole.GOVERNMENT]: {
      gradient: "from-blue-600 to-indigo-600",
      bg: "bg-blue-50 dark:bg-blue-950/30",
      text: "text-blue-700 dark:text-blue-300",
      border: "border-blue-200 dark:border-blue-700",
      icon: "🏛️",
      label: "Government",
    },
    [UserRole.PRIVATE]: {
      gradient: "from-emerald-600 to-teal-600",
      bg: "bg-emerald-50 dark:bg-emerald-950/30",
      text: "text-emerald-700 dark:text-emerald-300",
      border: "border-emerald-200 dark:border-emerald-700",
      icon: "🏢",
      label: "Verified",
    },
    [UserRole.ADMIN]: {
      gradient: "from-purple-600 to-violet-600",
      bg: "bg-purple-50 dark:bg-purple-950/30",
      text: "text-purple-700 dark:text-purple-300",
      border: "border-purple-200 dark:border-purple-700",
      icon: "👮",
      label: "Admin",
    },
    [UserRole.CITIZEN]: {
      gradient: "from-gray-600 to-slate-600",
      bg: "bg-gray-50 dark:bg-gray-800/30",
      text: "text-gray-700 dark:text-gray-300",
      border: "border-gray-200 dark:border-gray-600",
      icon: "👤",
      label: "Citizen",
    },
  },
};
